### ISSUE TITLE
pika.exceptions.AMQPConnectionError

### ISSUE THREAD

**Issue by ZhuangweiKang** [doc-vu/fecbench-server-docker#1]
The following error happened sometimes.
```
root@isislab11:/home/ubuntu# docker logs 2eacb3e70458
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
waiting for the queue:
Done starting the Thread!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/src/app/amqp_collector/amqp_listener.py", line 341, in run
    self._connection.ioloop.start()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 496, in start
    self.process_timeouts()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 366, in process_timeouts
    timer['callback']()
  File "/usr/local/lib/python3.6/site-packages/pika/connection.py", line 1836, in _on_connect_timer
    error)
  File "/usr/local/lib/python3.6/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/usr/local/lib/python3.6/site-packages/pika/connection.py", line 1768, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 172.28.0.4:5672 failed: [Errno 111] Connection refused

```

**Comment by ZhuangweiKang** [comment]
Seems like client times out before server is ready. The [sleep](https://github.com/doc-vu/fecbench-server-docker/blob/58e628322e2f32a4e10e172773bb8fc16d88fab6/pycollector/run_cmd.sh#L3) time is not enough.

Similar issue was post [here]( https://stackoverflow.com/questions/46219760/pika-exceptions-connectionclosed-connection-to-172-18-0-35672-failed-errno-1)

**Comment by yogeshVU** [comment]
Yes, perhaps that could be made as an entry argument to the docker-compose script.

**Comment by yogeshVU** [comment]
@ZhuangweiKang  can you update it here? https://github.com/doc-vu/fecbench-server-docker/blob/58e628322e2f32a4e10e172773bb8fc16d88fab6/docker-compose.yml#L25

**Comment by ZhuangweiKang** [comment]
@yogeshVU I don't write permission for the repository.

**Comment by ZhuangweiKang** [comment]
Add sleep as an arg of run_cmd.sh, which value is set in docker-compose.yml
